<?php

namespace NostalgiazBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUsers()
	{
		$query =$this->_em->createQuery('
			SELECT u
			FROM NostalgiazBundle:Utilisateur u' );

		return $query->getResult();
	}


}
