<?php

namespace NostalgiazBundle\Repository;

/**
 * UtilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends \Doctrine\ORM\EntityRepository
{
	public function getUsers()
	{

		$queryBuilder = $this->_em->createQueryBuilder()
      	->select('a')
      	->from($this->_entityName, 'a');

      	$query = $queryBuilder->getQuery();
      	$results = $query->getResult();
      	
      	return $results;

	}


}
